### ISSUE TITLE
Could you please upload the Deeplab with VGG-16 backbone?

### ISSUE THREAD

**Issue by an-other** [PengtaoJiang/OAA-PyTorch#10]
Thank  you for great work!
Could you please upload the Deeplab with VGG-16 backbone if you are convenient?
Thanks.

**Comment by an-other** [comment]
Hi,I find DeeplabV1 with VGG-16 backbone but I can't find the DeeplabV2 with VGG-16 backbone.
I wonder if they have a big difference?

**Comment by PengtaoJiang** [comment]
Hi, @an-other, there is no difference between them. I just utilize the off-the-shelf deeplab-PyTorch code as our segmentation code.  The original DeepLab v1 with VGG-16 backbone is Caffe code.

**Comment by an-other** [comment]
Thanks for reply!I will have a try.Have a nice day :)
