### ISSUE TITLE
Qualitative segmentation results

### ISSUE THREAD

**Issue by potato9991** [PengtaoJiang/OAA-PyTorch#12]
Can you provide the code that generates the qualitative segmentation results?

**Comment by PengtaoJiang** [comment]
In gen_gt.py, you can find the following code at L101-104,
    out = Image.fromarray(out.astype(np.uint8), mode='P')
    out.putpalette(palette)
    out_name = save_path + name + '.png'
    out.save(out_name)
'out' denotes the output of the segmentation network.
