### ISSUE TITLE
train_cls.txt missing

### ISSUE THREAD

**Issue by ErikStammes** [PengtaoJiang/OAA-PyTorch#4]
Hi, when running `./train_iam.sh`, it tries to load the file `../Classification/data/VOCdevkit/VOC2012/ImageSets/Segmentation/train_cls.txt`, which is not in this repository and also not in the original Pascal VOC 2012 dataset. Can you upload this file?

Furthermore, in the installation instructions the following packages are missing:
- torchvision
- opencv-python

**Comment by PengtaoJiang** [comment]
Hi, @ErikStammes  The augmented voc dataset with 10582 training images is [here](https://drive.google.com/file/d/1uh5bWXvLOpE-WZUUtO77uwCB4Qnh6d7X/view).   The `train_cls.txt` is in `VOCdevkit/VOC2012/ImageSets/Segmentation/train_cls.txt`. You can obtain useful information from our [OAA](https://github.com/PengtaoJiang/OAA).

**Comment by PengtaoJiang** [comment]
@ErikStammes  Thanks for your suggestion.

**Comment by ErikStammes** [comment]
Thanks for the clarifications!
