### ISSUE TITLE
The segmentation results

### ISSUE THREAD

**Issue by zwy1996** [PengtaoJiang/OAA-PyTorch#6]
Hi,

Nice work! I am sorry to bother you, when I used your pytorch code of oaa, I executed all instructions that you offered but I couldn't get the segmentation results, should I  use something code of caffe version or I need to executed other instructions?

Thanks very much!

**Comment by PengtaoJiang** [comment]
Hi, the oaa-pytorch code only enables the online attention accumulation process. You can use the proxy code to generate proxy labels then train a deeplab model.

发件人：zwy1996 <notifications@github.com>
发送日期：2020-12-05 16:23:17
收件人：PengtaoJiang/OAA-PyTorch <OAA-PyTorch@noreply.github.com>
抄送人：Subscribed <subscribed@noreply.github.com>
主题：[PengtaoJiang/OAA-PyTorch] The segmentation results (#6)

Hi,
Nice work! I am sorry to bother you, when I used your pytorch code of oaa, I executed all instructions that you offered but I couldn't get the segmentation results, should I use something code of caffe version or I need to executed other instructions?
Thanks very much!

**Comment by zwy1996** [comment]
OK, Thank you very much!
