### ISSUE TITLE
saliency_aug在数据集里面有吗

### ISSUE THREAD

**Issue by shi-10** [PengtaoJiang/OAA-PyTorch#8]

**Comment by PengtaoJiang** [comment]
你好 你下载数据集https://drive.google.com/file/d/1jnHE6Sau0tHI7X6JQKhzHov-vseYbrf9/view, 在VOCdevkit/VOC2012/ 目录下有saliency_aug

发件人：shi-10 ***@***.***>
发送日期：2021-06-22 13:59:20
收件人：PengtaoJiang/OAA-PyTorch ***@***.***>
抄送人：Subscribed ***@***.***>
主题：[PengtaoJiang/OAA-PyTorch] saliency_aug在数据集里面有吗 (#8)

**Comment by shi-10** [comment]
下载需要访问权限

**Comment by PengtaoJiang** [comment]
我修改了权限，你试下可以吗？

发件人：shi-10 ***@***.***>
发送日期：2021-06-22 14:16:13
收件人：PengtaoJiang/OAA-PyTorch ***@***.***>
抄送人：Jiangpengtao ***@***.***>,Comment ***@***.***>
主题：Re: [PengtaoJiang/OAA-PyTorch] saliency_aug在数据集里面有吗 (#8)

下载需要访问权限

**Comment by shi-10** [comment]
OK可以了，谢谢

**Comment by fangyihui-1** [comment]
你好 下载数据集https://drive.google.com/file/d/1jnHE6Sau0tHI7X6JQKhzHov-vseYbrf9/view时发现是空的，现在要去下载saliency_aug，到哪去下载

**Comment by fangyihui-1** [comment]
@PengtaoJiang
