### ISSUE TITLE
训练分割网络

### ISSUE THREAD

**Issue by shi-10** [PengtaoJiang/OAA-PyTorch#9]
我生成了伪标签之后，我怎么用这个伪标签来训练deeplab-pytorch啊？

**Comment by PengtaoJiang** [comment]
你好， 按照deeplab-pytorch配置下， 然后把VOC2012/SegmentationClassAug 文件夹用你的伪标签代替，训练分割网络。

发件人：shi-10 ***@***.***>
发送日期：2021-06-24 15:18:33
收件人：PengtaoJiang/OAA-PyTorch ***@***.***>
抄送人：Subscribed ***@***.***>
主题：[PengtaoJiang/OAA-PyTorch] 训练分割网络 (#9)

我生成了伪标签之后，我怎么用这个伪标签来训练deeplab-pytorch啊？

**Comment by PengtaoJiang** [comment]
如果有困难， 我稍后会把deeplab-pytorch 的训练过程上传上去，期待你的回信。

发件人：shi-10 ***@***.***>
发送日期：2021-06-24 15:18:33
收件人：PengtaoJiang/OAA-PyTorch ***@***.***>
抄送人：Subscribed ***@***.***>
主题：[PengtaoJiang/OAA-PyTorch] 训练分割网络 (#9)

**Comment by PengtaoJiang** [comment]
@shi-10 ，我重新更新了code和ReadMe, 把 deeplab-pytorch 的训练也加入进来了，如果有问题，请反馈给我。

**Comment by shi-10** [comment]
好的，十分感谢

**Comment by shi-10** [comment]
bash scripts/setup_caffemodels.sh中
wget -nc -P ./data http://liangchiehchen.com/projects/released/deeplab_aspp_resnet101/prototxt_and_model.zip

这一行你在代码中给注释掉了

**Comment by PengtaoJiang** [comment]
我修改下，我当时觉得wget下载不下来，直接从链接下载了。
